//! Sparkle 2 updater integration.
//!
//! Sparkle is loaded dynamically instead of being linked at Rust build time. This keeps
//! `cargo run`/unit tests usable on a checkout that does not contain the native framework yet,
//! while a bundled `.app` automatically gets the real updater when `Sparkle.framework` is copied
//! into `Contents/Frameworks`.

use crate::log_info;
use objc2::runtime::{AnyClass, AnyObject, Sel};
use objc2::sel;
use std::ffi::{c_char, c_void, CString};
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

/// The stable HTTPS endpoint that will host the appcast on the project's R2 custom domain.
///
/// `appcast.xml` is deliberately not generated by this repository. The release owner can
/// publish it later without changing the application binary or the Rust updater code.
pub(crate) const FEED_URL: &str = "https://download.oh-my-tab.app/appcast.xml";

const RTLD_NOW: i32 = 2;

extern "C" {
    fn objc_msgSend();
    fn dlopen(filename: *const c_char, mode: i32) -> *mut c_void;
}

/// Sparkle controller is retained for the lifetime of the process. The framework handle is also
/// intentionally kept open; unloading an Objective-C framework while its objects are alive is
/// unsafe. These pointers are only touched on AppKit's main thread.
struct UpdaterState {
    _framework_handle: *mut c_void,
    controller: *mut AnyObject,
}

unsafe impl Send for UpdaterState {}
unsafe impl Sync for UpdaterState {}

static STATE: OnceLock<Mutex<Option<UpdaterState>>> = OnceLock::new();

fn state() -> &'static Mutex<Option<UpdaterState>> {
    STATE.get_or_init(|| Mutex::new(None))
}

unsafe fn send_id(receiver: *mut AnyObject, selector: Sel) -> *mut AnyObject {
    type Fn = unsafe extern "C" fn(*mut AnyObject, Sel) -> *mut AnyObject;
    let f: Fn = std::mem::transmute(objc_msgSend as *const ());
    f(receiver, selector)
}

unsafe fn send_id3(
    receiver: *mut AnyObject,
    selector: Sel,
    first: bool,
    second: *mut AnyObject,
    third: *mut AnyObject,
) -> *mut AnyObject {
    type Fn = unsafe extern "C" fn(
        *mut AnyObject,
        Sel,
        bool,
        *mut AnyObject,
        *mut AnyObject,
    ) -> *mut AnyObject;
    let f: Fn = std::mem::transmute(objc_msgSend as *const ());
    f(receiver, selector, first, second, third)
}

unsafe fn send_void(receiver: *mut AnyObject, selector: Sel) {
    type Fn = unsafe extern "C" fn(*mut AnyObject, Sel);
    let f: Fn = std::mem::transmute(objc_msgSend as *const ());
    f(receiver, selector)
}

unsafe fn send_void_bool(receiver: *mut AnyObject, selector: Sel, value: bool) {
    type Fn = unsafe extern "C" fn(*mut AnyObject, Sel, bool);
    let f: Fn = std::mem::transmute(objc_msgSend as *const ());
    f(receiver, selector, value)
}

fn framework_candidates() -> Vec<PathBuf> {
    let mut paths = Vec::new();
    if let Ok(path) = std::env::var("SPARKLE_FRAMEWORK_PATH") {
        if !path.trim().is_empty() {
            let path = PathBuf::from(path);
            paths.push(if path.extension().is_some_and(|ext| ext == "framework") {
                path.join("Sparkle")
            } else {
                path
            });
        }
    }

    if let Ok(executable) = std::env::current_exe() {
        if let Some(contents) = executable.parent().and_then(Path::parent) {
            paths.push(contents.join("Frameworks/Sparkle.framework/Sparkle"));
            paths.push(contents.join("PrivateFrameworks/Sparkle.framework/Sparkle"));
        }
    }

    paths.push(PathBuf::from(
        "/Library/Frameworks/Sparkle.framework/Sparkle",
    ));
    paths
}

unsafe fn load_framework() -> *mut c_void {
    // The class may already be registered when a host app loaded Sparkle for us.
    if AnyClass::get(c"SPUStandardUpdaterController").is_some() {
        return std::ptr::null_mut();
    }

    for path in framework_candidates() {
        let path_string = path.to_string_lossy();
        let Ok(c_path) = CString::new(path_string.as_bytes()) else {
            continue;
        };
        let handle = dlopen(c_path.as_ptr(), RTLD_NOW);
        if !handle.is_null() {
            return handle;
        }
    }
    std::ptr::null_mut()
}

/// Start Sparkle if its framework is available in the current app bundle.
///
/// This is idempotent. Returning `false` means the app is running without Sparkle (for example,
/// a raw `cargo run` or a dev bundle built before the framework was copied), not that the app
/// itself failed to start.
pub(crate) fn initialize(automatically_check: bool) -> bool {
    let mut guard = state().lock().unwrap();
    if let Some(current) = guard.as_ref() {
        unsafe {
            let updater = send_id(current.controller, sel!(updater));
            if !updater.is_null() {
                send_void_bool(
                    updater,
                    sel!(setAutomaticallyChecksForUpdates:),
                    automatically_check,
                );
            }
        }
        return true;
    }

    let framework_handle = unsafe { load_framework() };
    let Some(controller_class) = AnyClass::get(c"SPUStandardUpdaterController") else {
        log_info!(
            "Sparkle updater unavailable: Sparkle.framework not found; expected {}",
            framework_candidates().first().map_or_else(
                || "Contents/Frameworks/Sparkle.framework".to_string(),
                |p| p.display().to_string()
            )
        );
        return false;
    };

    let controller = unsafe {
        let class_object = controller_class as *const AnyClass as *mut AnyObject;
        let allocated = send_id(class_object, sel!(alloc));
        send_id3(
            allocated,
            sel!(initWithStartingUpdater:updaterDelegate:userDriverDelegate:),
            true,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
        )
    };
    if controller.is_null() {
        log_info!("Sparkle updater failed to initialize its standard controller");
        return false;
    }

    unsafe {
        let updater = send_id(controller, sel!(updater));
        if !updater.is_null() {
            send_void_bool(
                updater,
                sel!(setAutomaticallyChecksForUpdates:),
                automatically_check,
            );
        }
        send_void(controller, sel!(startUpdater));
    }

    *guard = Some(UpdaterState {
        _framework_handle: framework_handle,
        controller,
    });
    log_info!(
        "Sparkle updater started (automatic checks: {}, feed: {})",
        automatically_check,
        FEED_URL
    );
    true
}

/// Apply the About-page automatic-check setting to a running Sparkle updater.
pub(crate) fn set_automatic_checks(enabled: bool) {
    let guard = state().lock().unwrap();
    let Some(current) = guard.as_ref() else {
        return;
    };
    unsafe {
        let updater = send_id(current.controller, sel!(updater));
        if !updater.is_null() {
            send_void_bool(updater, sel!(setAutomaticallyChecksForUpdates:), enabled);
        }
    }
    log_info!("Sparkle automatic update checks set to {}", enabled);
}

/// Ask Sparkle to present its standard update UI. Returns `false` when Sparkle is not loaded.
pub(crate) fn check_for_updates() -> bool {
    // Be defensive for smoke tests or an unusual launch path that invokes the About action
    // before the normal startup sequence has reached updater initialization.
    if state().lock().unwrap().is_none() {
        let automatically_check = crate::config::CONFIG
            .read()
            .map(|cfg| cfg.updates.automatically_check)
            .unwrap_or(true);
        if !initialize(automatically_check) {
            return false;
        }
    }
    let guard = state().lock().unwrap();
    let Some(current) = guard.as_ref() else {
        return false;
    };
    unsafe {
        type Fn = unsafe extern "C" fn(*mut AnyObject, Sel, *mut AnyObject);
        let f: Fn = std::mem::transmute(objc_msgSend as *const ());
        f(
            current.controller,
            sel!(checkForUpdates:),
            std::ptr::null_mut(),
        );
    }
    true
}
